### ISSUE TITLE
Missing lines while stream pushing too fast

### ISSUE THREAD

**Issue by JasinYip** [lucagrulla/node-tail#115] opened 2020-11-04 06:33 UTC
While the file been watching writing too fast, the read stream might miss some lines.

The fallowing code would reproduce the issue.

```js
const fs = require('fs')
const exec = require('child_process').execSync;
const { Tail } = require('tail');

const bufferPath = __dirname + '/buffer.log';
const outputPath = __dirname + '/output.log';

exec(`echo "" > ${bufferPath}`);
exec(`echo "" > ${outputPath}`);

const tail = new Tail(bufferPath);
tail.on('line', line => fs.appendFileSync(outputPath, line + '\r\n'));

// write input file
let input = [];
for (let i = 0; i < 100; i++) {
  input.push(`${i}: {a:1,b:2}\r\n`)
}

input.forEach((msg) => fs.appendFile(bufferPath, msg, () => {}))
```

As we can see the `output.log` had less than 100 lines. Bigger number we set to for-loop, more lines would been missed.

![image](https://user-images.githubusercontent.com/7105264/98076885-1a553f00-1eaa-11eb-8a2a-e707887fbb72.png)

This might cause Node.js streaming usage problem, we might should use pipeline instead of `on('data', cb)`

**Backpressuring in Streams** - https://nodejs.org/en/docs/guides/backpressuring-in-streams/

**Comment by nicolas-goudry** [comment] 2020-12-11 08:53
@JasinYip you might want to check out [this package](https://github.com/g-script/better-tail) then.

@lucagrulla I hope this is cool with you :ok_hand:

**Comment by JasinYip** [comment] 2020-12-14 06:27
@nicolas-goudry You are amazing, man! I will try it later.

**Comment by lucagrulla** [comment] 2020-12-21 15:20
Hi @JasinYip , 
I cannot reproduce the bug. I did push the loop to 500000 and everything works as expected.
Which version of node are you using?

**Comment by lucagrulla** [comment] 2020-12-21 15:25
> @lucagrulla I hope this is cool with you 👌
Hi @nicolas-goudry, great to see node-tail library triggered more OSS work. 

Out of curiosity: what's the main difference from your point of view?

**Comment by nicolas-goudry** [comment] 2020-12-21 16:11
> Hi @JasinYip ,
> I cannot reproduce the bug. I did push the loop to 500000 and everything works as expected.
> Which version of node are you using?

I can confirm I can reproduce this bug using node 14 on Linux.

> Out of curiosity: what's the main difference from your point of view?

Main difference is I’m using `ReadableStream` rather than `EventEmitter`. But it also has several features that `node-tail` haven’t, such as:
- `bytes/lines` which allows you to target last _N_ bytes/lines of content (or **from** _N_ byte/line of content until end)
- `retry` which allows you to retry opening file if it’s inaccessible (customizable)

The main downsides of my implementation compared to yours are:
- it can’t keep track of a file which is renamed. In fact, I didn’t even tested this use case.
- it doesn’t support other line separators than `\r`, `\n` or `\r\n` (maybe I will come down to it)

As you can see in the README, I first tried to tweak `node-tail` (after rewriting it in pure JS) but I stumbled on the same error @JasinYip encountered.

**Comment by lucagrulla** [comment] 2020-12-21 17:49
Thanks @nicolas-goudry.
I'll try with Linux and node 14.On MacOS and node 15 it works fine.

What do you mean with "using ReadableStream rather than EventEmitter"?
`node-tail` use streams to read content and emits events to communicate upstream. 
Is it not the  approach used in `better-tail`as well?

**Comment by nicolas-goudry** [comment] 2020-12-21 18:05
@lucagrulla Maybe it's related to Linux 🤷🏻‍♂️ I used provided example and got some lines mixed (in the middle and at the end of the file).

Yes, `node-tail` uses streams to read content, but not to output it, that's what does `better-tail`: it returns a stream that can be listened to (like `node-tail`), but also piped.

**Comment by lucagrulla** [comment] 2020-12-22 08:23
@nicolas-goudry:
I did test on Ubuntu and node 14 and I still could not replicate the issue. Mixed lines is different from missing lines: in the example above lines are mixed, but it's the producer that causing it, not the consumer.

On stream as aoutcome: It's a good idea. It's been indeed in the backlog for quite some time.

**Comment by lucagrulla** [comment] 2021-01-02 15:48
Although I tested on multiple OSes I can't replicate the issue.
Closing it.

**Closed by lucagrulla** 2021-01-02 15:48 UTC
