### ISSUE TITLE
Error compiling in Electron

### ISSUE THREAD

**Issue by gautejohan** [lucagrulla/node-tail#78] opened 2018-10-17 09:00 UTC
Hi,
great work with tail!

I get the following error when trying to use the package within an Electron application:
Error: ./node_modules/tail/lib/tail.js [0] Module parse failed: Unexpected token (66:126)

It is probably something to do with my webpack config, but I haven't been able to figure out what's wrong.

Line 66 in tail.js looks like this:
({separator: this.separator = /[\r]{0,1}\n/, fsWatchOptions: this.fsWatchOptions = {}, fromBeginning = false, follow: this.follow = true, logger: this.logger, useWatchFile: this.useWatchFile = false, flushAtEOF: this.flushAtEOF = false, encoding: this.encoding = "utf-8"} = options);

If I split this line to one per variable it works. I guess there is some coffee script magic I don't know.

I'll continue to try to configure the webpack configuration.

**Comment by viyaha** [comment] 2018-10-23 10:16
hi,

I have the same issue with pkg. After investigating the issue it seems like there is a problem with "fromBeginning = false". Changing it to "fromBeginning: fromBeginning = false" fixes the issue.

==> I have no idea about coffee script so I cannot create a pull requet, sorry...

**Comment by resistance-is-futile** [comment] 2018-10-23 20:52
This worked for me with the error i was having in electron. Is this something that can be submitted as a pull request?

**Comment by lucagrulla** [comment] 2018-10-24 06:29
I have no experience with Electron. 

How do you include the library? 
Are you not including the npm package?

**Comment by gautejohan** [comment] 2018-10-24 06:37
We use npm and typescript. It could be the version of ecmascript we are using, the error occurs during compile.

**Comment by viyaha** [comment] 2018-10-24 06:37
I'm using it with npm, the issue is the compiled JS-File:

As NPM installs it:

![image](https://user-images.githubusercontent.com/44086665/47410952-9bc85180-d767-11e8-83f2-95d311586f23.png)

Executing the issue in the Browser F12 (another example of the issue, just to better visualize the issue):

![image](https://user-images.githubusercontent.com/44086665/47411060-e21db080-d767-11e8-9ba8-85dcf3aa7350.png)

**Comment by lucagrulla** [comment] 2018-10-24 06:45
I still don't understand the problem.
Latest version of the library works fine, so we need to understand what's difference when in Electron/webpack.

Which version of node are you using?
Can you share a redacted version of your webpack?

**Comment by lucagrulla** [comment] 2018-10-24 07:03
The dev tool screenshot is irrelevant. 
The syntax there is just wrong: in that case you are creating an object and assign it to var options, hence the wrong syntax ({fromBeginning=false} is not a valid object syntax).

Current assumption is that the library destructuring code fails to compile.

**Comment by viyaha** [comment] 2018-10-24 07:31
Steps to reproduce (for pkg, should be the same in electron):

index.js:
`require('tail');`


```
npm install tail pkg
.\node_modules\.bin\pkg index.js
```

**Comment by lucagrulla** [comment] 2018-10-24 08:42
The problem is not with the syntax/coffeescript transpilation, otherwise it should failed consistently (and it's not happening). 

The issue has to be in the webpack/babel interaction with the library.
If someone can reproduce wit hclarity around:
* node version
* webpack configuration
* babel configuration

Then it would be great.

**Comment by viyaha** [comment] 2018-10-24 08:48
That means you could not reproduce the issue with [https://github.com/lucagrulla/node-tail/issues/78#issuecomment-432544967](url) ? (it used pkg instead of electron because of the faster reproduction setup, electron and pkg have the same issue)

==>
- Node Version 10.12.0
- no webpack
- no babel

**Comment by lucagrulla** [comment] 2018-10-24 09:14
I can replicate the issue with:
https://github.com/lucagrulla/node-tail/issues/78#issuecomment-432544967

Still, the Coffeescript/JS syntax is correct. 
The problem happens from the specific ecosystem used for packaging up tail with electron/pkg.

It might be worth to check if there's an open issue with any of these projects.

I'll have a look at this in more details, but I have no timeline on looking into this one.

**Comment by viyaha** [comment] 2018-10-24 10:31
Simple moving fromBeginning = false to the end of the object deconstructing) fixes the parsing issue in pkg (and most likly in electron too).

I still don't have any idea whats wrong in the parsing (and who is responsible), but in the meantime it would be nice to have this small quickfix.

**Comment by gautejohan** [comment] 2018-10-24 10:53
[Coffe script fixed](https://coffeescript.org/#try:events%20%3D%20require(%22events%22)%0Afs%20%3D%20require('fs')%0A%0Aenvironment%20%3D%20process.env%5B'NODE_ENV'%5D%20%7C%7C%20'development'%0A%0Aclass%20Tail%20extends%20events.EventEmitter%0A%20%20readBlock%3A%20%3D%3E%0A%20%20%20%20if%20%40queue.length%20%3E%3D%201%0A%20%20%20%20%20%20block%20%3D%20%40queue%5B0%5D%0A%20%20%20%20%20%20if%20block.end%20%3E%20block.start%0A%20%20%20%20%20%20%20%20stream%20%3D%20fs.createReadStream(%40filename%2C%20%7Bstart%3Ablock.start%2C%20end%3Ablock.end-1%2C%20encoding%3A%20%40encoding%7D)%0A%20%20%20%20%20%20%20%20stream.on%20'error'%2C(error)%20%3D%3E%0A%20%20%20%20%20%20%20%20%20%20%40logger.error(%22Tail%20error%3A%20%23%7Berror%7D%22)%20if%20%40logger%0A%20%20%20%20%20%20%20%20%20%20%40emit('error'%2C%20error)%0A%20%20%20%20%20%20%20%20stream.on%20'end'%2C%3D%3E%0A%20%20%20%20%20%20%20%20%20%20x%20%3D%20%40queue.shift()%0A%20%20%20%20%20%20%20%20%20%20%40internalDispatcher.emit(%22next%22)%20if%20%40queue.length%20%3E%200%0A%20%20%20%20%20%20%20%20%20%20if%20%40flushAtEOF%20%26%26%20%40buffer.length%20%3E%200%0A%20%20%20%20%20%20%20%20%20%20%20%20%40emit(%22line%22%2C%20%40buffer)%0A%20%20%20%20%20%20%20%20%20%20%20%20%40buffer%20%3D%20''%0A%20%20%20%20%20%20%20%20stream.on%20'data'%2C%20(data)%20%3D%3E%0A%20%20%20%20%20%20%20%20%20%20if%20%40separator%20is%20null%0A%20%20%20%20%20%20%20%20%20%20%20%20%40emit(%22line%22%2C%20data)%0A%20%20%20%20%20%20%20%20%20%20else%0A%20%20%20%20%20%20%20%20%20%20%20%20%40buffer%20%2B%3D%20data%0A%20%20%20%20%20%20%20%20%20%20%20%20parts%20%3D%20%40buffer.split(%40separator)%0A%20%20%20%20%20%20%20%20%20%20%20%20%40buffer%20%3D%20parts.pop()%0A%20%20%20%20%20%20%20%20%20%20%20%20%40emit(%22line%22%2C%20chunk)%20for%20chunk%20in%20parts%0A%0A%20%20constructor%3A(filename%2C%20options%20%3D%20%7B%7D)%20-%3E%0A%20%20%20%20super%20filename%2C%20options%0A%20%20%20%20%40filename%20%3D%20filename%0A%20%20%20%20%7B%40separator%20%3D%20%2F%5B%5Cr%5D%7B0%2C1%7D%5Cn%2F%2C%20%20%40fsWatchOptions%20%3D%20%7B%7D%2C%0A%20%20%20%20%40follow%20%3D%20true%2C%20%40logger%2C%20%40useWatchFile%20%3D%20false%2C%20%40flushAtEOF%20%3D%20false%2C%20%40encoding%20%3D%20%22utf-8%22%2CfromBeginning%20%3D%20false%7D%20%3D%20options%0A%0A%20%20%20%20if%20%40logger%0A%20%20%20%20%20%20%40logger.info(%22Tail%20starting...%22)%0A%20%20%20%20%20%20%40logger.info(%22filename%3A%20%23%7B%40filename%7D%22)%0A%20%20%20%20%20%20%40logger.info(%22encoding%3A%20%23%7B%40encoding%7D%22)%0A%0A%20%20%20%20%40buffer%20%3D%20''%0A%20%20%20%20%40internalDispatcher%20%3D%20new%20events.EventEmitter()%0A%20%20%20%20%40queue%20%3D%20%5B%5D%0A%20%20%20%20%40isWatching%20%3D%20false%0A%0A%20%20%20%20%40internalDispatcher.on%20'next'%2C%3D%3E%0A%20%20%20%20%20%20%40readBlock()%0A%0A%20%20%20%20%40watch(fromBeginning)%0A%0A%20%20change%3A%20(filename)%20%3D%3E%0A%20%20%20%20%20%20try%0A%20%20%20%20%20%20%20%20stats%20%3D%20fs.statSync(filename)%0A%20%20%20%20%20%20catch%20err%0A%20%20%20%20%20%20%20%20%40logger.error(%22'%23%7Be%7D'%20event%20for%20%23%7Bfilename%7D.%20%23%7Berr%7D%22)%20if%20%40logger%0A%20%20%20%20%20%20%20%20%40emit(%22error%22%2C%20%22'%23%7Be%7D'%20event%20for%20%23%7Bfilename%7D.%20%23%7Berr%7D%22)%0A%20%20%20%20%20%20%20%20return%0A%20%20%20%20%20%20%40pos%20%3D%20stats.size%20if%20stats.size%20%3C%20%40pos%20%23scenario%20where%20texts%20is%20not%20appended%20but%20it's%20actually%20a%20w%2B%0A%20%20%20%20%20%20if%20stats.size%20%3E%20%40pos%0A%20%20%20%20%20%20%20%20%40queue.push(%7Bstart%3A%20%40pos%2C%20end%3A%20stats.size%7D)%0A%20%20%20%20%20%20%20%20%40pos%20%3D%20stats.size%0A%20%20%20%20%20%20%20%20%40internalDispatcher.emit(%22next%22)%20if%20%40queue.length%20is%201%0A%0A%20%20watch%3A%20(fromBeginning)%20-%3E%0A%20%20%20%20return%20if%20%40isWatching%0A%20%20%20%20%0A%20%20%20%20if%20%40logger%0A%20%20%20%20%20%20%40logger.info(%22filesystem.watch%20present%3F%20%23%7Bfs.watch%20isnt%20undefined%7D%22)%0A%20%20%20%20%20%20%40logger.info(%22useWatchFile%3A%20%23%7B%40useWatchFile%7D%22)%0A%20%20%20%20%20%20%40logger.info(%22fromBeginning%3A%20%23%7BfromBeginning%7D%22)%0A%0A%20%20%20%20%40isWatching%20%3D%20true%0A%20%20%20%20try%0A%20%20%20%20%20%20stats%20%3D%20%20fs.statSync(%40filename)%0A%20%20%20%20catch%20err%0A%20%20%20%20%20%20%40logger.error(%22watch%20for%20%23%7B%40filename%7D%20failed%3A%20%23%7Berr%7D%22)%20if%20%40logger%0A%20%20%20%20%20%20%40emit(%22error%22%2C%20%22watch%20for%20%23%7B%40filename%7D%20failed%3A%20%23%7Berr%7D%22)%0A%20%20%20%20%20%20return%0A%20%20%20%20%40pos%20%3D%20if%20fromBeginning%20then%200%20else%20stats.size%0A%20%20%20%20%0A%20%20%20%20if%20%40pos%20%3D%3D%200%0A%20%20%20%20%20%20%40change(%40filename)%0A%0A%20%20%20%20if%20%20not%20%40useWatchFile%20and%20fs.watch%0A%20%20%20%20%20%20%40logger.info(%22watch%20strategy%3A%20watch%22)%20if%20%40logger%0A%20%20%20%20%20%20%40watcher%20%3D%20fs.watch%20%40filename%2C%20%40fsWatchOptions%2C%20(e%2C%20filename)%20%3D%3E%20%40watchEvent%20e%2C%20filename%0A%20%20%20%20else%0A%20%20%20%20%20%20%40logger.info(%22watch%20strategy%3A%20watchFile%22)%20if%20%40logger%0A%20%20%20%20%20%20fs.watchFile%20%40filename%2C%20%40fsWatchOptions%2C%20(curr%2C%20prev)%20%3D%3E%20%40watchFileEvent%20curr%2C%20prev%0A%0A%20%20rename%3A%20(filename)%20-%3E%0A%20%20%20%20%20%20%23MacOS%20sometimes%20throws%20a%20rename%20event%20for%20no%20reason.%0A%20%20%20%20%20%20%23Different%20platforms%20might%20behave%20differently.%0A%20%20%20%20%20%20%23see%20https%3A%2F%2Fnodejs.org%2Fapi%2Ffs.html%23fs_fs_watch_filename_options_listener%0A%20%20%20%20%20%20%23filename%20might%20not%20be%20present.%0A%20%20%20%20%20%20%23https%3A%2F%2Fnodejs.org%2Fapi%2Ffs.html%23fs_filename_argument%0A%20%20%20%20%20%20%23Better%20solution%20would%20be%20check%20inode%20but%20it%20will%20require%20a%20timeout%20and%0A%20%20%20%20%20%20%23%20a%20sync%20file%20read.%0A%20%20%20%20%20%20if%20filename%20is%20undefined%20%7C%7C%20filename%20isnt%20%40filename%0A%20%20%20%20%20%20%20%20%40unwatch()%0A%20%20%20%20%20%20%20%20if%20%40follow%0A%20%20%20%20%20%20%20%20%20%20setTimeout%20(%3D%3E%20%40watch())%2C%201000%0A%20%20%20%20%20%20%20%20else%0A%20%20%20%20%20%20%20%20%20%20%40logger.error(%22'rename'%20event%20for%20%23%7B%40filename%7D.%20File%20not%20available.%22)%20if%20%40logger%0A%20%20%20%20%20%20%20%20%20%20%40emit(%22error%22%2C%20%22'rename'%20event%20for%20%23%7B%40filename%7D.%20File%20not%20available.%22)%0A%20%20%20%20%20%20else%0A%20%20%20%20%20%20%20%20%23%20%40logger.info(%22rename%20event%20but%20same%20filename%22)%0A%0A%20%20watchEvent%3A%20(e%2C%20evtFilename)%20-%3E%0A%20%20%20%20if%20e%20is%20'change'%0A%20%20%20%20%20%20%40change(%40filename)%0A%20%20%20%20else%20if%20e%20is%20'rename'%0A%20%20%20%20%20%20%40rename(evtFilename)%0A%0A%20%20watchFileEvent%3A%20(curr%2C%20prev)%20-%3E%0A%20%20%20%20if%20curr.size%20%3E%20prev.size%0A%20%20%20%20%20%20%40pos%20%3D%20curr.size%20%20%20%20%23%20Update%20%40pos%20so%20that%20a%20consumer%20can%20determine%20if%20entire%20file%20has%20been%20handled%0A%20%20%20%20%20%20%40queue.push(%7Bstart%3Aprev.size%2C%20end%3Acurr.size%7D)%0A%20%20%20%20%20%20%40internalDispatcher.emit(%22next%22)%20if%20%40queue.length%20is%201%0A%0A%20%20unwatch%3A%20-%3E%0A%20%20%20%20if%20%40watcher%0A%20%20%20%20%20%20%40watcher.close()%0A%20%20%20%20else%0A%20%20%20%20%20%20fs.unwatchFile%20%40filename%0A%20%20%20%20%40isWatching%20%3D%20false%0A%20%20%20%20%40queue%20%3D%20%5B%5D%0A%20%20%20%20%40logger.info(%22Unwatch%20%22%2C%20%40filename)%20if%20%40logger%0A%0Aexports.Tail%20%3D%20Tail)

See the above link, I can confirm what viyaha is saying, moving  `fromBeginning = false` to the end of the destructuring works.

This must be a bug in babel some how, see this [example](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=usage&spec=true&loose=true&code_lz=MYewdgzgLgBCAOUCW4IwLwwN4wgU3gEMAnQqEYgLhgHIBCGmAXwG4AoNgMwFcxhlwMKHmgAKBAMgBKbGxjyYANxIxOxEAFsAQngDmSMGAO72chaKxmFC_EVLkqQgBZIIAOlskyFDDAD0ANoAOsQAulgADAA0AIxMQWB-UVbWqhAA6mTATgDyiCiQ1FAu7pwZWbn5qL5YTMmpCmqaOvqGxr6chAA2-PUNqiBdXSAA7kUlbpyDwyO-UMTceH0Nw7q6eI7Frm6r68TLqdz4mVDZAGJIXXjj20d4J-eXeB3dvSnWnF1HTgCCUACiOTON1KXwgvwBQJePSW7wUeD4IAAJsYQW4EaAUWBdL4AETcKCcAC0AA5cQdrExfBIChApKZrKBIIM8DsQLpRAApADKOQAch55sYkJwAJ6iLYQKIwMDcIbSgBMUmlTW0egMRmx9LYTA4TOgMGGnE4vjAeFmwjENNQ2qAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env&prettier=false&targets=Electron-1.8%252CNode-8.9&version=6.26.0&envVersion=1.6.2):

**Comment by gautejohan** [comment] 2018-10-24 10:59
I've created a PR: https://github.com/lucagrulla/node-tail/pull/80 to work around babel issue.

**Comment by lucagrulla** [comment] 2018-10-24 13:39
Thanks @gautejohan , it does look like a Babel bug. 
I'm overall happy with the PR as well (it's neat and not intrusive). 

I'll merge PR and release new version as soon as I have time (i.e. not later then end of the week, most likely earlier than that).

**Closed** 2018-10-24 17:45 UTC
